### ISSUE TITLE
Course Section Picker: Fix conflict highlighting

### ISSUE THREAD

**Issue by BCYilex** [UTM-Hacklab/VIAplanner#107]
![image](https://user-images.githubusercontent.com/60441990/80439118-c7377980-88d3-11ea-8003-20eaa0776dd8.png)
P0102 conflicts with P0101, but it is not necessary to highlight it because if the user is to switch from P0101 to P0102, there shouldn't be a problem. Only the truly conflicting sections should be highlighted, either it's with a section of another course or a different type of activity of the same course.

**Comment by BCYilex** [comment]
Resolved with #119

**Comment by TheFatPanda97** [comment]
merged
