### ISSUE TITLE
Some of the courses do not have a valid time section, it needs to be cleaned up.

### ISSUE THREAD

**Issue by hejingy1** [UTM-Hacklab/VIAplanner#108]
![backend](https://user-images.githubusercontent.com/55768022/80442046-bcfe9500-893e-11ea-9372-997a35868289.jpg)

Not sure if there are more of these courses, how can we identify this in backend?

**Comment by leecohen23** [comment]
<img width="1440" alt="Screen Shot 2020-04-28 at 13 17 34" src="https://user-images.githubusercontent.com/48926652/80522715-a104ee80-8952-11ea-8934-de430dcc2de2.png">

works for me

**Comment by leecohen23** [comment]
<img width="1440" alt="Screen Shot 2020-04-28 at 13 19 42" src="https://user-images.githubusercontent.com/48926652/80522932-ef19f200-8952-11ea-92c7-fd423b70912d.png">

using the function method also works

**Comment by hejingy1** [comment]
umm, that's wired could it be the reason that mine graphql playground is not most updated version?

**Comment by BCYilex** [comment]
I've also checked, there doesn't seem to be a problem.
