### ISSUE TITLE
Section Switch Bug

### ISSUE THREAD

**Issue by TheFatPanda97** [UTM-Hacklab/VIAplanner#142]
# Overview

Currently switching a section, if there's a conflict, the course that you wish to switch sections will be deleted or no actions will be taken (even though there is a possible timetable)

**Comment by BCYilex** [comment]
![blah](https://user-images.githubusercontent.com/60441990/83446284-6e03be00-a41c-11ea-8a5e-c001a1a880c6.gif)
Switching this practical section is totally possible and this is not supposed to happen.
