### ISSUE TITLE
Full Year Courses Only Appear on Winter Timetable

### ISSUE THREAD

**Issue by TheFatPanda97** [UTM-Hacklab/VIAplanner#151]
# Overview

Currently, all full-year courses will be added as a winter course, rather than both semesters. 

![issue](https://user-images.githubusercontent.com/36747253/83905721-28066d00-a730-11ea-88d6-151413f97cd2.gif)

**Comment by BCYilex** [comment]
This will require drastic changes to the algorithm and front-end. We initially ignored the full-year course case to make it easier to present to Vincent, but we've since then forgotten about it.

I think this must be completed before the release of Beta
