### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by TheFatPanda97** [UTM-Hacklab/VIAplanner#160]
# Overview

Currently, our official name is UofT Course Tools. By using both the uoft logo as well as their name, we may run into trouble later down the line. Therefore, rebranding is needed. 

Please put your ideas on [this page](https://www.canva.com/design/DAD-huCP22k/share/preview?token=6kn_0sddLFWRNUvu0SclXQ&role=EDITOR&utm_content=DAD-huCP22k&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton)

**Comment by hejingy1** [comment]
Finished Logo and name design
