### ISSUE TITLE
Lock Time Bug

### ISSUE THREAD

**Issue by BCYilex** [UTM-Hacklab/VIAplanner#165]
Locking a time on Tuesday should not result in any changes to CSC207
![blahblah](https://user-images.githubusercontent.com/60441990/83986236-11b40900-a90a-11ea-9ca4-1b7856814095.gif)

**Comment by TheFatPanda97** [comment]
This is a design choice since the algo will always return the first timetable. In this case, did you switch the lecture for CSC207 first then tried to lock another time? If so, then this is the expected behaviour.

**Comment by BCYilex** [comment]
If this is a design decision, I recon changing it, because when I tested it with a friend, it really looked like a bug. It is counter-intuitive how locking an unrelated time will change the timetable. Maybe we can make it so that it only runs the algorithm when locking a whole day overwrites a class on that day.
