### ISSUE TITLE
Write UI component breakdowns for the Timetable Planner

### ISSUE THREAD

**Issue by ArsalaBangash** [UTM-Hacklab/VIAplanner#18]
## Overview

Once we've made our statechart diagram that describes the user's journey, we now have to describe the UI components involved in the journey, and how they interact with each other to build our system. 

Since we're working with [Vue components](https://www.youtube.com/watch?v=AhqJ95Y7-ko), a good way of brainstorming our application is taking stock of the data, methods, and subcomponents involved in a components. 

Having our components laid out and documented in this manner makes the transition into coding more graceful since pitfalls and poor design decisions can be identified earlier on before diving too deep into the code. 

### Data
The data that is:
- Rendered directly to the UI component 
- Used to indirectly define the behavior of the UI component

### Methods 
These are often functions that respond to events that the component is listening for. 

### SubComponents
These are the subcomponents inside of the component. Thinking about subcomponents early encourages composition.

**Comment by williamchau123** [comment]
Will we be using figma to design the visual components, or are we using the statechart to create abstract components first?
