### ISSUE TITLE
Course Time Flipped Back

### ISSUE THREAD

**Issue by BrianLi009** [UTM-Hacklab/VIAplanner#196]
When my friend is testing it, she first changed the fall timetable, after using the winter timetable for a bit, she went back to the fall. However, one of the course reverts its changes automatically and went back to the original time.

**Comment by TheFatPanda97** [comment]
Did she attempt to change a course that was full year?

**Comment by BrianLi009** [comment]
No it’s half year

**Comment by BCYilex** [comment]
Brian, can you recreate this bug and show us?

**Comment by BrianLi009** [comment]
![bug](https://user-images.githubusercontent.com/40159724/85905278-fafe2500-b7d8-11ea-8eeb-b3832d407a2c.gif)

**Comment by BrianLi009** [comment]
Notice ECO375

**Comment by TheFatPanda97** [comment]
hmm, I think the issue has to do with the algo selecting the first available timetable, so the initial state of the ECO375 is been re-selected. Unfortunately, this is unwanted, but expected behaviour. I would have to ask @williamchau123
