### ISSUE TITLE
Course Conflict Edge Case

### ISSUE THREAD

**Issue by TheFatPanda97** [UTM-Hacklab/VIAplanner#206]
# Overview

- There are some courses in which conflicts are inevitable, but the school specifically allows it because they are reserved for quizzes. For example MAT102H5F and MAT223H5S. 

![image](https://user-images.githubusercontent.com/36747253/85930887-fe9fb380-b88d-11ea-9257-e1bb332b0f12.png)

**Comment by logonoff** [comment]
fixed in #347
