### ISSUE TITLE
PHY241 cannot generate

### ISSUE THREAD

**Issue by BrianLi009** [UTM-Hacklab/VIAplanner#210]
Cannot generate timetable for PHY241, pls fix

**Comment by CursedKeyboard** [comment]
I believe this is a consequence of having both a tutorial and a practical. I am not well versed enough in javascript or whatever language is used to write the course parser so i am having a hard time pinpointing it.

**Comment by CursedKeyboard** [comment]
PHY245 also faces the same problem

**Comment by BrianLi009** [comment]
Hi! Yes that is exactly the problem since the algorithm will identify that as a tutorial and lab conflict. We are thinking of just making these courses "special case", since we cannot tweak with the actual algorithm, that will mess up the other courses.

**Comment by CursedKeyboard** [comment]
I suspect that this is a byproduct of not organizing the meeting sections in UTM-Hacklab/VIAplanner/blob/master/packages/courses-scraper/api/node/scraper.js. Perhaps doing some organization here will help you fix this issue (use lecture sections, practical sections, tutorial sections).

**Comment by logonoff** [comment]
fixed in #347
