### ISSUE TITLE
Use CORS to prevent unauthorized API use

### ISSUE THREAD

**Issue by darenliang** [UTM-Hacklab/VIAplanner#223]
I checked out the compiled javascript source and found that the API keys are hard-coded.

![github-issue](https://user-images.githubusercontent.com/44593263/86819560-d49c7d00-c055-11ea-8911-299c88fbd3bf.PNG)

Source I accessed: https://viaplanner.ca/js/app.4d1d29a9.js

This shouldn't be a problem, however, I was able to access the API using the key from a different domain, which people could abuse/ddos as the JSON payloads are pretty big.

I would suggest using an `Access-Control-Allow-Origin` response header to limit the API call to the viaplanner domain.

**Comment by TheFatPanda97** [comment]
@darenliang 
Thanks for catching that! Do you know if there is any way to hide the API key? Currently, I'm setting it as an environment variable and I thought it would be hidden.

**Comment by krishchow** [comment]
I would recommend for the time being to hotfix and disable the API endpoints for any CUD (create/update/delete) operations. If the API is read-only, this is not as significant of an issue. Right now, application functionality is at risk, but if it's read-only, the only risk that someone can make spam requests, something you can handle with a rate-limiting library

**Comment by darenliang** [comment]
To allow a given domain I think you can set the `Access-Control-Allow-Origin` response header to the origin domain.

This isn't completely foolproof, but clients/browsers enforce these rules so that it's harder to make API requests on unapproved domains.

Example: `Access-Control-Allow-Origin: https://viaplanner.ca`

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin

Edit: It looks like there's already the CORS middleware enabled. Changing the setting to only allow viaplanner's domain should work.

**Comment by darenliang** [comment]
Alternatively, you can use an express ratelimit middleware to limit the number of requests per IP.

https://www.npmjs.com/package/express-rate-limit

This node package seems pretty reputable. I believe viaplanner is using mongodb? If so, then express-rate-limit natively supports mongodb as a data store.

**Comment by TheFatPanda97** [comment]
I see the error in what I was doing before. Since vue is a client-side framework, even if I attempt to hide the API key as environment variables, it would be shown in the build files. The express server is actually using CORS right now, but I was being naive and allowed all domains to access it 😅. Thanks for the help guys!
