### ISSUE TITLE
8 am wont unlock as a full hour

### ISSUE THREAD

**Issue by williamchau123** [UTM-Hacklab/VIAplanner#246]
**Describe the bug**
When using the lock whole hour button at 8 am, trying to unlock it using the unlock whole hour is impossible.

**To Reproduce**
1. Lock Monday
2. Lock 8 am
3. Try to unlock 8 am
![Bug](https://user-images.githubusercontent.com/60441990/87277004-73d6cf80-c4af-11ea-8c16-b124bdd10149.gif)

**Extra Comment**
Other dynamic hours (such as 7/8/9 pm) does not have the same issue

**Comment by BCYilex** [comment]
Fixed
