### ISSUE TITLE
Export Bug

### ISSUE THREAD

**Issue by BrianLi009** [UTM-Hacklab/VIAplanner#251]
**Describe the bug**

**To Reproduce**
1. Go to 'MAT132H5F'
2. Select LEC0103
3. Click on 'export'
4. Check 'png'
5. overlap in lecture session

![Fall-Timetable (2)](https://user-images.githubusercontent.com/40159724/87566212-ad1a6580-c690-11ea-8d8c-c8f75fa40e6d.png)

**Comment by BCYilex** [comment]
Fixed.

**Comment by BCYilex** [comment]
Fixed.
