### ISSUE TITLE
Course colors too similar

### ISSUE THREAD

**Issue by BCYilex** [UTM-Hacklab/VIAplanner#257]
- The app assigns randomly generated colours to courses upon adding them, but sometimes the colours end up too similar: 
![image](https://user-images.githubusercontent.com/60441990/87614796-090bdb00-c6df-11ea-9d4c-7d0152fd5fd9.png)
- The chance of this increases as the user repeatedly adds and deletes courses.

Proposed solution: The app should avoid assigning colours that are too similar to an already existing colour.

Idea: colour difference can be calculated in sRGB with this formula: 
![image](https://user-images.githubusercontent.com/60441990/87623311-1e8b0000-c6f3-11ea-99cb-3bc3d40d08ab.png)

**Comment by darenliang** [comment]
I've noticed that VIAPlanner uses the `color-generator` npm package for color generation.

I would propose an alternate solution where you could create an approved list of handpicked colors and wrap it around methods that will prevent returning duplicates. Regardless of implementation, I think it is necessary to keep track of the list of colors currently used which will be annoying.

**Comment by BCYilex** [comment]
> I would propose an alternate solution where you could create an approved list of handpicked colors and wrap it around methods that will prevent returning duplicates. Regardless of implementation, I think it is necessary to keep track of the list of colors currently used which will be annoying.

Yea, that's probably our best choice. In fact, that's exactly what we had a while back, we should change back to it.

Calculating the color difference is not ideal because the same color difference can be easily distinguishable among blue-ish and red-ish colors but barely noticeable on green-ish colors.

**Comment by ggggg** [comment]
Assuming this was fixed in #268
