### ISSUE TITLE
UTSC section code length 

### ISSUE THREAD

**Issue by TheFatPanda97** [UTM-Hacklab/VIAplanner#262]
**Describe the bug**
UTSC courses have sections that only have 2 numbers instead of 4. This will cause it to not be displayed on the timetable

**To Reproduce**
1. choose ANTC59H3S 
2. the lecture cannot be chosen since it's only 3 letters

**Screenshots**
![issue](https://user-images.githubusercontent.com/36747253/87631149-d1178e80-c704-11ea-949a-2d8b67189192.gif)

**Comment by BCYilex** [comment]
All the ANTC courses have a longer course code, this can break many things, such as locking and deleting

**Comment by BCYilex** [comment]
The missing L01 has the wrong course code, and timetable event needs the course code to get course's colour, that is why it failed to render.
![Capture](https://user-images.githubusercontent.com/60441990/87862328-c3d4ec80-c91c-11ea-9bc2-3cfe77a2f888.PNG)
