### ISSUE TITLE
UTSG Timetable API is operational

### ISSUE THREAD

**Issue by camfairchild** [UTM-Hacklab/VIAplanner#284]
https://timetable.iit.artsci.utoronto.ca/api/20219/courses
Is operational
You can scrape the json using
GET https://timetable.iit.artsci.utoronto.ca/api/20219/courses?section=F
GET https://timetable.iit.artsci.utoronto.ca/api/20219/courses?section=S
GET https://timetable.iit.artsci.utoronto.ca/api/20219/courses?section=Y

might work with
GET https://timetable.iit.artsci.utoronto.ca/api/20219/courses?section=F,S,Y
@TheFatPanda97

**Comment by TheFatPanda97** [comment]
@camfairchild This is amazing! Do you know if this is something that recently came out?

**Comment by camfairchild** [comment]
Yea, its on the subreddit @TheFatPanda97

**Comment by camfairchild** [comment]
the API has always been used afaik, though

**Comment by TheFatPanda97** [comment]
Hmm, the only pity is that it's only for UTSG, currently, we are providing course selection for all 3 campuses so we won't be able to rely on just this API, but I think we might transition our UTSG portion to use this API. Thanks for letting us know!
