### ISSUE TITLE
Make timetable cell editable

### ISSUE THREAD

**Issue by HarshitGupta29** [UTM-Hacklab/VIAplanner#293]
Switching back and forth from your timetable to your task list could be quite tedious. If there was an optionality on each cell such that if we click pen button on it then it becomes an input box and then we could add a task in a simple text format. This would save a lot of time.

**Comment by TheFatPanda97** [comment]
Hi @HarshitGupta29, I am a bit confused about what is a "task". Could you elaborate on that?

**Comment by HarshitGupta29** [comment]
Hi @TheFatPanda97 let's say I want to commute from utm to utsg, at 5pm, so I could click on pen button on 5pm cell and could write commute - utm to utsg. Like wise i could add my daily tasks like assignments and stuff. This way I wouldn't need to switch to my task list.

**Comment by TheFatPanda97** [comment]
> Hi @TheFatPanda97 let's say I want to commute from utm to utsg, at 5pm, so I could click on pen button on 5pm cell and could write commute - utm to utsg. Like wise i could add my daily tasks like assignments and studd

Oh I see, so a feature that would allow for you to add custom events during the day right? That would be useful, for now what you could do is block off the times you don't wish for us to schedule by clicking on the unavailable cell.

**Comment by ggggg** [comment]
Blocking timeslots is good enough.
