### ISSUE TITLE
Sections that are closed until further notice show up in VIAplanner

### ISSUE THREAD

**Issue by robertmotr** [UTM-Hacklab/VIAplanner#298]
Tutorial sections that show up as closed until further notice on the official UTM timetable planner website show up as sections that you are able to select in your schedule on VIAplanner.

1. Search for MAT137Y5 on the search bar.
2. Click on MAT137Y5 to change the tutorial section.
3. Select T9102
4. When verifying T9102 on UTM's official timetable website, you will notice that this section is in fact closed.

**Comment by TheFatPanda97** [comment]
ah that is my bad, should be fixed pretty soon

**Comment by TheFatPanda97** [comment]
Should be fixed, thanks for the heads up!
