### ISSUE TITLE
API Request or a way to extract list of UTM courses for a specific department.

### ISSUE THREAD

**Issue by flyingwalrushippo** [UTM-Hacklab/VIAplanner#330]
Hello I'm doing some work to generate schedules for a specific department at UTM. I was looking for a way to scrape the course data from ttb.utoronto.ca that would have all the course info for the upcoming winter semester for a specific department. Could you guys point me in how i should approach this? I've heard you guys already have an API for this very sort of course scraping. Any help would be much appreciated.

**Comment by TheFatPanda97** [comment]
Hey @flyingwalrushippo, so I wrote a new script a few months ago to parse the ttb API and store them as JSON data for viaplanner. You can find the parser here: https://github.com/VIAplanner/via-scrapers/blob/master/packages/courses-scraper/api/ttb/index.js. Since you are looking to grab the data for a specific department, you may have to modify the script slightly to filter for that. Hopefully that helps 👍

**Comment by flyingwalrushippo** [comment]
Hey thanks for the response, much appreciated. I've been looking at your code and i'm trying to run it on my local machine here. However i keep getting errors regarding the 'import course from '....api/structures/course', and for MeetingSection, Time. Seems like NodeJS isn't recognizing these javascript files. I've got all the NPM modules installed and the directory basically cloned.

**Comment by TheFatPanda97** [comment]
hmm I just ran the script and it seems to be working fine. Can you try the following steps and see if it works?

1. Clone the repo
`git clone https://github.com/VIAplanner/via-scrapers`

2. Install the necessary packages
```
cd packages/courses-scraper
npm install
``` 

3. Run the setup script
```
chmod u+x setup.bash (you may need this if you get a permission error)
./setup.bash
```

4. Run the scrape command
`npm run ttb`

If all goes well, you should get `allCourseCodes.json` and a `courses` containing JSONs regarding each course in the `output` folder

**Comment by flyingwalrushippo** [comment]
Thank you for this amazing writeup, it indeed fixed my issue. Everything is working smoothly on my linux machine. Eternally grateful for your hard work on viaplanner.

**Comment by flyingwalrushippo** [comment]
Just a small question, does the scraper only output one meeting time for each course, in each individual course JSON.
