### ISSUE TITLE
Documentation for the Demo at the show

### ISSUE THREAD

**Issue by ArsalaBangash** [UTM-Hacklab/VIAplanner#34]
## Overview
Just as we wrote documentation for the overall product, we should now write documentation for the demo so we have a clear picture before we start the implementation. 
Steps involved are the following:

- Outline the user journey for the demo at The Show.
**e.g.** Select Year -> Select program -> Select Courses -> Optimize Timetable -> Export?
- Outline the data structures and components involved.

**Comment by ArsalaBangash** [comment]
@BCYilex and @lilJDoesntknow , @BrianLi009  and @williamchau123 . You all need to get together and replicate the process of 

user journey -> mvp features -> components

For our demo at the show.

**Comment by BrianLi009** [comment]
I would focus a bit more on the actual layout of our table during the show. For example, whether we need a poster besides having our laptop there, and how would be present during the 5 minutes spotlight
