### ISSUE TITLE
Certain courses wont be added.

### ISSUE THREAD

**Issue by Maksym-W** [UTM-Hacklab/VIAplanner#344]
Certain courses, such as PHY241, wont be added on the timetable. I think this is because for that kind of course, practicals and tutorials happen at the same time, but alternate every week. On the timetable, since this would cause a conflict, nothing happens. Can conflicts be allowed on the website?

**Comment by ggggg** [comment]
Related to #339

**Comment by logonoff** [comment]
fixed in #347
