### ISSUE TITLE
You can add unavailable lecture sections 

### ISSUE THREAD

**Issue by troanoven** [UTM-Hacklab/VIAplanner#361]
On VIAPlanner you're able to select and add lecture and tutorial sections that are unavailable to your schedule. For example, CSC236H5F's lecture 0103 and tutorial 108 are both unavailable on ttb, but you can add them to your schedule on VIAPlanner.

**Comment by ggggg** [comment]
![image](https://github.com/VIAplanner/via-timetable/assets/25105662/749cf486-04ec-42b4-aca5-9c1054b23f4f)
TTB screenshot for reference
