### ISSUE TITLE
Outdated Installation Instructions

### ISSUE THREAD

**Issue by ghost** [UTM-Hacklab/VIAplanner#367]
The current Github repo URL is listed as "https://github.com/UTM-Hacklab/VIAplanner.git" under the "UTM-Hacklab" organization.

However, the URL should be https://github.com/VIAplanner/VIAplanner.git, under the "VIAplanner" organization.

Furthermore, the Readme suggests cd'ing to the "packages/app" directory inside the repo, however, this directory is nonexistent.

The `yarn` and `yarn serve` commands run correctly in the root directory of the repo.

**Comment by ggggg** [comment]
Good catch!
