### ISSUE TITLE
Setup a deployment system for the documentation website

### ISSUE THREAD

**Issue by ArsalaBangash** [UTM-Hacklab/VIAplanner#5]
### Background

The docs folder will be in /packages/docs 

In our previous repo, the documentation was at the root of the repo. Now, the source for the docs will be in /packages/docs , and we will have to write a build system that builds the source from /packages/docs and copies it over to /docs

### Notes
We could probably trigger a Github actions script or a CircleCI script to build and deploy the website every time there is a successful commit to the repo's master branch

**Comment by williamchau123** [comment]
### Notes

In the build script inside package.json, add cp ./docs ../docs to move the complied docs in master/packages/docs to master/docs

### Later implementation

Use CircleCI to make auto-deployment based on successful pull request
