### ISSUE TITLE
Revamp Course API documentation tab

### ISSUE THREAD

**Issue by ArsalaBangash** [UTM-Hacklab/VIAplanner#50]
Now that we have our course api up, let's revamp our documentation. 

Requirements: 
- Give a usage guide for the course api
- Link to graphql tutorials for those who have never worked with GraphQL
- Fix the heading to Course API
- Replace Data Structures with GraphQL models
- Add a section for GraphQL queries

**Comment by leecohen23** [comment]
everything has changed except for the last point
