### ISSUE TITLE
Add instructor name and course name for meeting sections as the output of the timetable algorithm

### ISSUE THREAD

**Issue by BCYilex** [UTM-Hacklab/VIAplanner#68]
So far each meeting section is missing an instructor name and a course name field that the TimetableCourseCard component needs to display
![image](https://user-images.githubusercontent.com/60441990/77477962-973c1880-6df3-11ea-879d-42e8e9c7a101.png)

**Comment by williamchau123** [comment]
This can be also issued to course api to see if they can provide meeting section times with instructor and course code.

**Comment by williamchau123** [comment]
## Request
Under Graphql's query, when calling meeting section times, the course code and instructor is also the attributes of the time object.
So when its being called, the data structure is:
{
course code: String,
Meeting Sections: [
{
section code: String,
times:[
{
course code: String, (this is a combination of section code and course code)
start: int,
end: int
}
]
}
]
}
