### ISSUE TITLE
Add invalid times constraint to Timetable planner

### ISSUE THREAD

**Issue by ArsalaBangash** [UTM-Hacklab/VIAplanner#8]
### Background

Now that we have a timetable planner that tells us if a configuration of courses is valid, the next step is constraining what we consider a valid time in a week. 

### Notes

We can have another parameter passed into our timetable validator function that holds a collection of invalid times. If the student wants Monday off, the invalidTimes collection would hold all of Monday's times.

**Comment by BrianLi009** [comment]
We will be treating "invalid time" as another course in terms of formatting so that the program will be clean and concise.
